version: "2"

linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - funcorder
    - funlen
    - ireturn
    - godot
    - godox
    - lll
    - revive
    - varnamelen
    - wsl
    - errcheck
    - err113
    - staticcheck
    - wrapcheck
    - mnd
    - gosec
    - errchkjson